# Generated by Django 5.2.3 on 2025-06-26 07:06

import uuid
from datetime import timedelta

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from apps.users.models import CustomUser
from django.contrib.auth.models import Group


def seed_users(apps, schema_editor):
    admin_group, _ = Group.objects.get_or_create(name="Admins")

    admin = CustomUser.objects.create(
        id=uuid.uuid4(),
        username="admin",
        email="admin@example.com",
        password=make_password("admin123"),
        first_name="Admin",
        last_name="User",
        last_seen=timezone.now(),
        is_staff=True,
        is_superuser=True,
    )
    admin.groups.add(admin_group)

    member_group, _ = Group.objects.get_or_create(name="Members")

    member = CustomUser.objects.create(
        id=uuid.uuid4(),
        username="member1",
        email="member@example.com",
        password=make_password("member123"),
        first_name="Regular",
        last_name="Member",
        last_seen=timezone.now() - timedelta(hours=2),
    )
    member.groups.add(member_group)

    # Create another member
    member2 = CustomUser.objects.create(
        id=uuid.uuid4(),
        username="member2",
        email="member2@example.com",
        password=make_password("member123"),
        first_name="Another",
        last_name="Member",
        last_seen=timezone.now() - timedelta(days=1),
    )
    member2.groups.add(member_group)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_users)]
