# Generated by Django 5.2.3 on 2025-06-26 07:06

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from apps.projects.models import Project
from apps.tasks.models import Task


def setup_admin():
    admin_group, _ = Group.objects.get_or_create(name="Admins")

    project_content_type = ContentType.objects.get_for_model(Project)
    task_content_type = ContentType.objects.get_for_model(Task)

    # Project permissions for Admin
    add_project, _ = Permission.objects.get_or_create(
        codename="add_project",
        name="Can add project",
        content_type=project_content_type,
    )
    change_project, _ = Permission.objects.get_or_create(
        codename="change_project",
        name="Can change project",
        content_type=project_content_type,
    )
    delete_project, _ = Permission.objects.get_or_create(
        codename="delete_project",
        name="Can delete project",
        content_type=project_content_type,
    )
    view_project, _ = Permission.objects.get_or_create(
        codename="view_project",
        name="Can view project",
        content_type=project_content_type,
    )

    # Task permissions for Admin
    add_task, _ = Permission.objects.get_or_create(
        codename="add_task", name="Can add task", content_type=task_content_type
    )
    change_task, _ = Permission.objects.get_or_create(
        codename="change_task", name="Can change task", content_type=task_content_type
    )
    delete_task, _ = Permission.objects.get_or_create(
        codename="delete_task", name="Can delete task", content_type=task_content_type
    )
    view_task, _ = Permission.objects.get_or_create(
        codename="view_task", name="Can view task", content_type=task_content_type
    )

    admin_group.permissions.add(
        add_project,
        change_project,
        delete_project,
        view_project,
        add_task,
        change_task,
        delete_task,
        view_task,
    )


# Member can only view projects and tasks
def setup_member():
    member_group, _ = Group.objects.get_or_create(name="Members")

    project_content_type = ContentType.objects.get_for_model(Project)
    task_content_type = ContentType.objects.get_for_model(Task)

    member_view_project, _ = Permission.objects.get_or_create(
        codename="view_project",
        name="Can view project",
        content_type=project_content_type,
    )
    member_view_task, _ = Permission.objects.get_or_create(
        codename="view_task", name="Can view task", content_type=task_content_type
    )

    member_group.permissions.add(member_view_project, member_view_task)


def create_group_and_permissions(apps, schema_editor):
    setup_admin()
    setup_member()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_group_and_permissions)]
